services:
  - type: web
    name: relo-prototype
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
