import { useEffect, useState } from 'react';
import * as client from '../../app/auth/auth-client';
import { useAuth } from '../../app/auth/AuthProvider';

export function SettingsPage() {
  const { session } = useAuth();
  const [preferences, setPreferences] = useState<client.PreferencesView | null>(null);
  const [notifications, setNotifications] = useState<client.NotificationView[]>([]);
  const [message, setMessage] = useState('');
  useEffect(() => { if (!session) return; void client.getPreferences(session.accessToken).then((result) => setPreferences(result.preferences)); void client.getNotifications(session.accessToken).then((result) => setNotifications(result.items)).catch(() => undefined); }, [session]);
  async function save() { if (!session || !preferences) return; try { const result = await client.updatePreferences(session.accessToken, { timezone: preferences.timezone, email: preferences.channels.email, inApp: preferences.channels.inApp, push: preferences.channels.push, shareContact: preferences.privacy.shareContact }); setPreferences(result.preferences); setMessage('Settings saved'); } catch { setMessage('Settings could not be saved'); } }
  async function markRead(id: string) { if (!session) return; await client.markNotificationRead(session.accessToken, id); setNotifications((current) => current.map((item) => item.id === id ? { ...item, readAt: new Date().toISOString() } : item)); }
  return <div className="page-content employee-page"><div className="page-heading"><div><p className="eyebrow">Your controls</p><h1>Settings</h1></div><p>Make Relo fit your rhythm. Changes only affect your workspace.</p></div>{preferences && <section className="settings-layout"><div className="panel settings-panel"><p className="eyebrow">Notifications</p><h2>Choose your signal</h2><label className="toggle-row"><span><strong>Email notifications</strong><small>Useful updates and programme changes</small></span><input aria-label="Email notifications" type="checkbox" checked={preferences.channels.email} onChange={(event) => setPreferences({ ...preferences, channels: { ...preferences.channels, email: event.target.checked } })} /></label><label className="toggle-row"><span><strong>In-app notifications</strong><small>Keep updates in your Relo inbox</small></span><input aria-label="In-app notifications" type="checkbox" checked={preferences.channels.inApp} onChange={(event) => setPreferences({ ...preferences, channels: { ...preferences.channels, inApp: event.target.checked } })} /></label><label className="toggle-row"><span><strong>Share contact details</strong><small>Allow sharing only when you confirm a request</small></span><input aria-label="Share contact details" type="checkbox" checked={preferences.privacy.shareContact} onChange={(event) => setPreferences({ ...preferences, privacy: { ...preferences.privacy, shareContact: event.target.checked } })} /></label><button className="button button-primary" type="button" onClick={() => void save()}>Save settings</button></div><div className="panel settings-panel"><p className="eyebrow">Inbox</p><h2>Recent updates</h2><div className="notification-list">{notifications.length === 0 ? <p className="muted">You are all caught up.</p> : notifications.map((notification) => <button className={`notification-row${notification.readAt ? ' is-read' : ''}`} type="button" key={notification.id} onClick={() => notification.readAt ? undefined : void markRead(notification.id)}><span className="notification-dot" aria-hidden="true" /><span><strong>{notification.title}</strong><small>{notification.body}</small></span></button>)}</div></div></section>}{message && <div className="status-line" role="status">{message}</div>}</div>;
}
