import { createSupabaseClient, type SupabaseClientConfig } from '../identity/supabase.js';
import { ApiError } from '../shared/errors.js';
import type { ReviewItem, ReviewDraftInput, ReviewRepository, ReviewerSettingsPatch } from './content-service.js';

function unavailable(): ApiError { return new ApiError(503, 'REVIEW_DATA_UNAVAILABLE', 'Review data is unavailable.'); }
function mapEntry(value: unknown): ReviewItem {
  if (!value || typeof value !== 'object') throw unavailable();
  const row = value as Record<string, any>; const provider = row.provider ?? {}; const city = provider.city ?? {};
  return { id: String(row.id), providerId: String(row.provider_id), cityId: String(provider.city_id ?? ''), cityName: String(city.name ?? ''), category: String(provider.category ?? ''), providerName: String(provider.name ?? ''), title: String(row.title), description: String(row.description), sourceUrl: typeof row.source_url === 'string' ? row.source_url : null, status: row.status, publishedAt: typeof row.published_at === 'string' ? row.published_at : null, expiresAt: typeof row.expires_at === 'string' ? row.expires_at : null, updatedAt: String(row.updated_at) };
}
const select = 'id, provider_id, title, description, source_url, published_at, expires_at, status, updated_at, provider:providers!inner(city_id, category, name, city:cities(name))';
export function makeSupabaseReviewRepository(client: ReturnType<typeof createSupabaseClient>): ReviewRepository {
  return {
    async getScope(userId) { const result = await client.from('review_assignments').select('city_id, category').eq('reviewer_user_id', userId).eq('active', true); if (result.error) throw unavailable(); return { cityIds: (result.data ?? []).map((row) => String(row.city_id)), categories: [...new Set((result.data ?? []).map((row) => String(row.category ?? '')).filter(Boolean))] }; },
    async listQueue(input) { let query = client.from('directory_entries').select(select, { count: 'exact' }).in('status', input.status ? [input.status] : ['draft', 'published']).order('updated_at', { ascending: false }).range((input.page - 1) * input.pageSize, input.page * input.pageSize - 1); const result = await query; if (result.error) throw unavailable(); return { items: (result.data ?? []).map(mapEntry), total: result.count ?? 0 }; },
    async getEntry(entryId) { const result = await client.from('directory_entries').select(select).eq('id', entryId).maybeSingle(); if (result.error) throw unavailable(); return result.data ? mapEntry(result.data) : null; },
    async saveDraft(input) { const result = await client.from('directory_entries').insert({ provider_id: input.providerId, title: input.title, description: input.description, source_url: input.sourceUrl ?? null, expires_at: input.expiresAt ?? null, status: 'draft' }).select(select).single(); if (result.error) throw unavailable(); return mapEntry(result.data); },
    async updateEntry(entryId, patch) { const values: Record<string, unknown> = {}; if (patch.title !== undefined) values.title = patch.title; if (patch.description !== undefined) values.description = patch.description; if (patch.sourceUrl !== undefined) values.source_url = patch.sourceUrl; if (patch.expiresAt !== undefined) values.expires_at = patch.expiresAt; const result = await client.from('directory_entries').update(values).eq('id', entryId).select(select).maybeSingle(); if (result.error) throw unavailable(); return result.data ? mapEntry(result.data) : null; },
    async publishEntry(entryId) { const result = await client.from('directory_entries').update({ status: 'published', published_at: new Date().toISOString() }).eq('id', entryId).select(select).maybeSingle(); if (result.error) throw unavailable(); return result.data ? mapEntry(result.data) : null; },
    async unpublishEntry(entryId) { const result = await client.from('directory_entries').update({ status: 'archived' }).eq('id', entryId).select(select).maybeSingle(); if (result.error) throw unavailable(); return result.data ? mapEntry(result.data) : null; },
    async getSettings(userId) { const result = await client.from('reviewer_settings').select('city_ids, categories, timezone, notification_settings').eq('reviewer_user_id', userId).maybeSingle(); if (result.error) throw unavailable(); if (!result.data) return null; return { cityIds: result.data.city_ids ?? [], categories: result.data.categories ?? [], timezone: String(result.data.timezone), channels: { email: result.data.notification_settings?.email !== false, inApp: result.data.notification_settings?.inApp !== false } }; },
    async updateSettings(userId, patch) { const values = { reviewer_user_id: userId, city_ids: patch.cityIds ?? [], categories: patch.categories ?? [], timezone: patch.timezone ?? 'UTC', notification_settings: patch.channels ?? { email: true, inApp: true } }; const result = await client.from('reviewer_settings').upsert(values, { onConflict: 'reviewer_user_id' }).select('city_ids, categories, timezone, notification_settings').single(); if (result.error) throw unavailable(); return { cityIds: result.data.city_ids, categories: result.data.categories, timezone: result.data.timezone, channels: { email: result.data.notification_settings?.email !== false, inApp: result.data.notification_settings?.inApp !== false } }; },
  };
}
export function createSupabaseReviewRepositoryFromEnv(accessToken: string): ReviewRepository { const url = process.env.SUPABASE_URL; const publishableKey = process.env.SUPABASE_PUBLISHABLE_KEY; if (!url || !publishableKey || !accessToken.trim()) throw unavailable(); const config: SupabaseClientConfig = { url, publishableKey, accessToken: accessToken.trim() }; return makeSupabaseReviewRepository(createSupabaseClient(config)); }
